name = "Expanded Storage Testing"
author = "Kneelawk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fddff6b87b4bd75aa28cea149ba2be8e4300861511a8c6733a87afdf7c2d957b"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"
